name: Plugin Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container: discourse/discourse_test:slim-browsers

    timeout-minutes: 30

    env:
      DISCOURSE_HOSTNAME: www.example.com
      RUBY_GLOBAL_METHOD_CACHE_SIZE: 131072
      RAILS_ENV: test
      PGUSER: discourse
      PGPASSWORD: discourse

    steps:
      - uses: actions/checkout@v4
        with:
          repository: discourse/discourse
          fetch-depth: 1

      - name: Install plugin
        uses: actions/checkout@v4
        with:
          path: plugins/discourse-plugin-scryfall
          fetch-depth: 1

      - name: Setup Git
        run: |
          git config --global user.email "ci@ci.invalid"
          git config --global user.name "Discourse CI"

      - name: Setup Bundler
        run: |
          gem install bundler --conservative -v $(awk '/BUNDLED WITH/ { getline; gsub(/ /,""); print $0 }' Gemfile.lock)
          bundle config --local path vendor/bundle
          bundle config --local deployment true
          bundle config --local without development

      - name: Bundler cache
        uses: actions/cache@v4
        id: bundler-cache
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Setup gems
        run: |
          bundle install --jobs 4
          bundle clean

      - name: Get yarn cache directory
        id: yarn-cache-dir
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Yarn cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Yarn install
        run: yarn install

      - name: Fetch app state cache
        uses: actions/cache@v4
        id: app-cache
        with:
          path: tmp/app-cache
          key: >-
            ${{ hashFiles('.github/workflows/tests.yml') }}-
            ${{ hashFiles('db/**/*', 'plugins/**/db/**/*') }}-

      - name: Restore database from cache
        if: steps.app-cache.outputs.cache-hit == 'true'
        run: psql -f tmp/app-cache/cache.sql postgres

      - name: Restore uploads from cache
        if: steps.app-cache.outputs.cache-hit == 'true'
        run: rm -rf public/uploads && cp -r tmp/app-cache/uploads public/uploads

      - name: Create and migrate database
        if: steps.app-cache.outputs.cache-hit != 'true'
        run: |
          bin/rake db:create
          bin/rake db:migrate

      - name: Create app cache
        if: steps.app-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p tmp/app-cache
          pg_dumpall > tmp/app-cache/cache.sql
          cp -r public/uploads tmp/app-cache/uploads

      - name: Check spec existence
        id: check_spec
        shell: bash
        run: |
          shopt -s globstar
          if [ 0 -eq $(find plugins/discourse-plugin-scryfall/spec -type f \( -name "*.rb" \) 2> /dev/null | wc -l) ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          fi

      - name: Plugin RSpec
        if: steps.check_spec.outputs.skip != 'true'
        run: bin/rake plugin:spec[discourse-plugin-scryfall]

      - name: Check QUnit existence
        id: check_qunit
        shell: bash
        run: |
          shopt -s globstar
          if [ 0 -eq $(find plugins/discourse-plugin-scryfall/test -type f \( -name "*.js" -not -path "*/node_modules/*" \) 2> /dev/null | wc -l) ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          fi

      - name: Plugin QUnit
        if: steps.check_qunit.outputs.skip != 'true'
        run: QUNIT_EMBER_CLI=1 bin/rake plugin:qunit[discourse-plugin-scryfall,'1200000']
        timeout-minutes: 10

      - name: Eslint
        if: ${{ !cancelled() }}
        run: |
          yarn --cwd plugins/discourse-plugin-scryfall lint:js

      - name: Prettier
        if: ${{ !cancelled() }}
        run: |
          yarn --cwd plugins/discourse-plugin-scryfall prettier -c .

      - name: Stylelint
        if: ${{ !cancelled() }}
        run: |
          yarn --cwd plugins/discourse-plugin-scryfall lint:css